namespace: sbarbett
name: pihole
version: "2.0.0"
readme: README.md
authors:
  - Shane Barbetta (Original)
  - Oriol Rius (Enhanced Fork)
description: >
  Enhanced Ansible collection for comprehensive Pi-hole v6 management.
  Features advanced domain management, DNS control, system monitoring,
  configuration backup/restore, and complete automation capabilities.
  Built on enhanced pihole6api fork with full API feature support.
license:
  - "MIT"
tags:
  - pihole
  - dns
  - networking
  - automation
  - monitoring
  - backup
  - security
dependencies: {}
repository: https://github.com/oriolrius/pihole-ansible
