---
- name: Process record on Pi-hole instance
  block:
    - name: Manage A record
      ansible.builtin.debug:
        msg: "Processing A record {{ record.name }} on {{ pihole_instance.name }}"

    - name: Manage A record
      sbarbett.pihole.local_a_record:
        host: "{{ record.name }}"
        ip: "{{ record.data }}"
        state: "{{ record.state }}"
        url: "{{ pihole_instance.name }}"
        password: "{{ pihole_instance.password }}"
      when: record.type == "A"

    - name: Manage AAAA record
      sbarbett.pihole.local_aaaa_record:
        host: "{{ record.name }}"
        ip: "{{ record.data }}"
        state: "{{ record.state }}"
        url: "{{ pihole_instance.name }}"
        password: "{{ pihole_instance.password }}"
      when: record.type == "AAAA"

    - name: Manage CNAME record
      ansible.builtin.debug:
        msg: "Processing CNAME record {{ record.name }} on {{ pihole_instance.name }}"

    - name: Manage CNAME record
      sbarbett.pihole.local_cname:
        host: "{{ record.name }}"
        target: "{{ record.data }}"
        ttl: "{{ record.ttl | default(300) }}"
        state: "{{ record.state }}"
        url: "{{ pihole_instance.name }}"
        password: "{{ pihole_instance.password }}"
      when: record.type == "CNAME"

    - name: Pause for 1 second
      ansible.builtin.command: sleep 1
      changed_when: false
      no_log: true
